import Head from 'next/head'
import Layout from '../components/Layout/Layout'

export default function Home() {
  return (
      <>
      <Head>
        <title>Dragtron - Technical Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>


      </Layout>
      </>    
  )
}
