import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout/Layout'
import styles from '../styles/Home.module.css'
import { BsArrowRightShort, } from "react-icons/bs";
import { BiSearch } from "react-icons/bi";
import { FcNext } from "react-icons/fc";
import Oval from '../public/assets/Oval.svg'
import Oval2 from '../public/assets/Oval2.svg'
import Square from '../public/assets/Square.svg'
import Rectangle from '../public/assets/Rectangle.svg'
import OvalFill from '../public/assets/OvalFill.svg'
import OvalFill2 from '../public/assets/OvalFill2.svg'
import Shape from '../public/assets/Shape.svg'
import Shape2 from '../public/assets/Shape2.svg'
import Collaboration from '../public/assets/Collaboration.svg'
import Transparency from '../public/assets/Transparency.svg'
import Trust from '../public/assets/Trust.svg'
import Integrity from '../public/assets/Integrity.svg'
import Wave from '../public/assets/Wave.svg'
import IconChecklist from '../public/assets/IconChecklist.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dragtron - Technical Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section id={styles.hero}>
          <div className={styles.content}>
            <h1>Come to join Us!</h1>
            <p>From year to year we strive to invent the most innovative technology that is used by both small enterprises and space enterprises.</p>
            <button>See Current Opening <BsArrowRightShort size={30} /></button>
          </div>
          <div className={styles.oval}>
            <Image src={Oval} alt="oval" />
          </div>
          <div className={styles.square}>
            <Image src={Square} alt="square" />
          </div>
          <div className={styles.square2}>
            <Image src={Square} alt="square" />
          </div>
          <div className={styles.group}>
            <Image src={OvalFill} alt="OvalFill" />
          </div>
          <div className={styles.shape}>
            <Image src={Shape} alt="shape" />
          </div>
        </section>

        <section id={styles.values}>
          <div className={styles.title}>
            <h1>A few things you should know about Us.</h1>
          </div>

          <div className={styles.container_values}>
            <div className={styles.left}>
              <h1>Our values</h1>
              <p>We strive to redefine the standard of excellence.</p>
            </div>

            <div className={styles.right}>
              <div className={styles.values_card}>
                <Image src={Collaboration} alt="Collaboration" width={64} height={64} />
                <h2>Collaboration</h2>
                <p>Collaboration is the process of two or more people or organizations working together to complete a task or achieve a goal. </p>
              </div>

              <div className={styles.values_card}>
                <Image src={Transparency} alt="Collaboration" width={64} height={64} />
                <h2>Transparency</h2>
                <p>Transparency, as used in science is operating in such a way that it is easy for others to see what actions are performed. </p>
              </div>

              <div className={styles.values_card}>
                <Image src={Trust} alt="Collaboration" width={64} height={64} />
                <h2>Trust</h2>
                <p>Trust will help us foster a positive and productive environment that delivers value to our users and customers. </p>
              </div>

              <div className={styles.values_card}>
                <Image src={Integrity} alt="Collaboration" width={64} height={64} />
                <h2>Integrity</h2>
                <p>Integrity is the practice of showing a consistent and uncompromising adherence to strong moral and ethical principles. </p>
              </div>

            </div>
          </div>

          <div className={styles.group2}>
            <Image src={OvalFill2} alt="OvalFill2" />
          </div>

          <div className={styles.wave}>
            <Image src={Wave} alt="Wave" />
          </div>
        </section>

        <section id={styles.team}>
          <div className={styles.oval2}>
            <Image src={Oval2} alt="Oval2" />
          </div>

          <div className={styles.shape2}>
            <Image src={Shape2} alt="shape" />
          </div>

          <div className={styles.list}>
            <div className={styles.item1}>
              <Image src={Square} alt="square" width={314} height={336} />
            </div>
            <div className={styles.item2}>
              <Image src={Square} alt="square" width={314} height={336} />
            </div>
            <div className={styles.item3}>
              <Image src={Square} alt="square" width={314} height={336} />
            </div>
            <div className={styles.item4}>
              <Image src={Square} alt="square" width={314} height={336} />
            </div>
          </div>

          <div className={styles.team_title}>
            <h1>Who We Are</h1>
            <p>We’re equal parts left and right brained. And we’re generally likeable. We won’t bored you with more adjectives. See for yourself.</p>
          </div>
        </section>

        <section id={styles.whatwedo}>
          <div className={styles.rectangle}>
            <Image src={Rectangle} alt="square" />
          </div>

          <div className={styles.whatwedo_content}>
            <h1>What we do</h1>
            <p>We supply enterprises, organizations and institutes of high-tech industries with modern components. We build long-term trusting relationships with our customers and partnes for further fruitful cooperations. <br /><br />
              From year to year we strive to invent the most innovative technology that is used by both small enterprises and space enterprises.</p>
          </div>
        </section>

        <section id={styles.join}>
          <div className={styles.wave2}>
            <Image src={Wave} alt="Wave" />
          </div>

          <div className={styles.rectangle2}>
            <Image src={Rectangle} alt="square" />
          </div>

          <div className={styles.join_content}>
            <span className={styles.badge}>COME JOIN US</span>
            <h1>Why Work Here</h1>
            <p>From year to year we strive to invent the most innovative technology.</p>
            <div className={styles.join_item}>
              <div className={styles.join_value}>
                <Image src={IconChecklist} alt="icon" />
                <div className={styles.join_detail}>
                  <h1>3500</h1>
                  <p>Visitors</p>
                </div>
              </div>

              <div className={styles.join_value}>
                <Image src={IconChecklist} alt="icon" />
                <div className={styles.join_detail}>
                  <h1>36</h1>
                  <p>Startups</p>
                </div>
              </div>

              <div className={styles.join_value}>
                <Image src={IconChecklist} alt="icon" />
                <div className={styles.join_detail}>
                  <h1>30</h1>
                  <p>Mentors</p>
                </div>
              </div>

              <div className={styles.join_value}>
                <Image src={IconChecklist} alt="icon" />
                <div className={styles.join_detail}>
                  <h1>8</h1>
                  <p>Countries</p>
                </div>
              </div>

              <div className={styles.join_value}>
                <Image src={IconChecklist} alt="icon" />
                <div className={styles.join_detail}>
                  <h1>6</h1>
                  <p>Stages</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id={styles.job}>
          <h1>Let’s find you an open position.</h1>
          <div className={styles.job_top}>
            <div className={styles.top_left}>
              <p>Find the right job for you no matter what it is that you do.</p>
            </div>

            <div className={styles.top_right}>
              <select id="location">
                <option value="all">All Location</option>
              </select>

              <div className={styles.search_bar}>
                <div className={styles.search_logo}>
                  <BiSearch size={20} color='#B3BAC5' />
                  <input type="text" placeholder="Search Positions" />
                </div>
                <button className={styles.button_inside}>Search</button>
              </div>
              <button className={styles.button_outside} >Get Started</button>
            </div>
          </div>

          <div className={styles.job_bottom}>
            <div className={styles.job_card}>
              <div className={styles.job_title}>
                <h2>UX Designer</h2>
                <p>New York, USA</p>
              </div>
              <FcNext />
            </div>

            <div className={styles.job_card}>
              <div className={styles.job_title}>
                <h2>UI Designer</h2>
                <p>Los Angeles, USA</p>
              </div>
              <FcNext />
            </div>

            <div className={styles.job_card}>
              <div className={styles.job_title}>
                <h2>Copy Writer</h2>
                <p>New York, USA</p>
              </div>
              <FcNext />
            </div>

            <div className={styles.job_card}>
              <div className={styles.job_title}>
                <h2>Front-End Designer</h2>
                <p>San Fransisco, CA, USA</p>
              </div>
              <FcNext />
            </div>

            <div className={styles.job_card}>
              <div className={styles.job_title}>
                <h2>Front-End Engineer</h2>
                <p>San Fransisco, CA, USA</p>
              </div>
              <FcNext />
            </div>

            <div className={styles.job_card}>
              <div className={styles.job_title}>
                <h2>Senior Back-end Developer</h2>
                <p>New York, USA</p>
              </div>
              <FcNext />
            </div>
          </div>
        </section>
      </Layout>
    </>
  )
}
