import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout/Layout'
import styles from '../styles/Home.module.css'
import { BsArrowRightShort } from "react-icons/bs";
import Oval from '../public/Oval.svg'
import Square from '../public/Square.svg'
import OvalFill from '../public/OvalFill.svg'
import Shape from '../public/Shape.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dragtron - Technical Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section id={styles.hero}>
          <div className={styles.content}>
            <h1>Come to join Us!</h1>
            <p>From year to year we strive to invent the most innovative technology that is used by both small enterprises and space enterprises.</p>
            <button>See Current Opening <BsArrowRightShort size={30} /></button>
          </div>
          <div className={styles.oval}>
            <Image src={Oval} alt="oval" />
          </div>
          <div className={styles.square}>
            <Image src={Square} alt="square" />
          </div>
          <div className={styles.square2}>
            <Image src={Square} alt="square" />
          </div>
          <div className={styles.group}>
            <Image src={OvalFill} alt="OvalFill" />
          </div>
          <div className={styles.shape}>
            <Image src={Shape} alt="shape" />
          </div>
        </section>
      </Layout>
    </>
  )
}
